Copy string before returning it
onnx/onnx-mlir pull request #1210
Opened 2022-03-01 20:49 UTC by etiotto

This PR fixes issue #1209.

Signed-off-by: Ettore Tiotto <etiotto@ca.ibm.com>

2022-03-02 03:07 UTC, etiotto commented on src/Compiler/OnnxMlirCompiler.cpp
> +  return strdup(val.c_str());
> The options are all in static area? So theoretically we should be able to return a pointer to the static area without doing a strdup?

The local variable `val` will go out of scope so if it copied the option string into a local buffer the memory the `char *` pointer points to will be gone.

2022-03-02 05:27 UTC, tungld commented on src/Compiler/OnnxMlirCompiler.cpp
> +  return strdup(val.c_str());
Can callers free a `const char*`?

2022-03-02 12:31 UTC, gongsu832 commented on src/Compiler/OnnxMlirCompiler.cpp
> +  return strdup(val.c_str());
> Can callers free a `const char*`?

You will get a compiler warning unless you cast away the `const` before calling `free`.

2022-03-02 16:32 UTC, gongsu832 commented on src/Compiler/OnnxMlirCompiler.cpp
> +  return strdup(val.c_str());
Not questioning whether strdup is needed or not. Yes in the current code it's needed. There is a bigger question than strdup. If we stick to static options, then we need to fix `omSetCompilerOptions` to be thread-safe. If you look at `CompilerUtils.cpp` there is a TODO comment above the static opts. So my point was that the whole static opts thing is probably not done properly and may need some restructure.

2022-03-03 15:52 UTC, etiotto commented on src/Compiler/OnnxMlirCompiler.cpp
> +  return strdup(val.c_str());
Ok we agree on the need for a strdup in that function, good.  Given that MLIR and LLVM use the `cl::opt` facilities to handle compiler option IMO we should do use the same facilities, which leaves us with the thread-safety issue you mentioned.  To address that issue I am going to use a `std::mutex` in `setCompilerOption` with will prevent a data race.

2022-03-05 11:04 UTC, gongsu832 commented on src/Compiler/OnnxMlirCompiler.cpp
> +  return strdup(val.c_str());
Can you put some comments on why we are adding the mutex?

2022-03-07 23:34 UTC, etiotto commented on src/Compiler/OnnxMlirCompiler.cpp
> +  return strdup(val.c_str());
done

2022-03-08 19:47 UTC, etiotto commented
@gongsu832 @AlexandreEichenberger can you pls take a look again ?

2022-03-09 15:12 UTC, AlexandreEichenberger requested changes

2022-03-09 15:21 UTC, gongsu832 commented
I respectfully disagree with removing the mutex. It's not to give a false sense of usability. Any time when you have multiple threads writing to shared data, serialization is the very basic requirement for not corrupting the shared data. The issue that one thread's changing the option will be seen by all other threads is a completely different issue and mutex is not even designed to protect against that.

2022-03-09 17:35 UTC, etiotto commented
> So I am requesting that

> the mutex is removed for now because they are marginally useful and giving a false sense of usability.
> we label the function in the interface as to be called only in a single thread mode

I have removed the mutex because is not essential to the main goal of this patch.  There is disagreement on what to do w.r.t. thread safety as per discussion above.  I do think that having a mutex does not make things worse, however in order to make progress I think we can agree on having the `strdup` and leave the discussion on thread safety to another time :-)

2022-03-09 18:35 UTC, AlexandreEichenberger approved these changes
LGTM, agree mutex is tangential to this.

2022-03-09 21:43 UTC, merged

2022-03-10 06:15 UTC, gongsu832 commented on src/Compiler/CompilerUtils.cpp
> +  static std::mutex mutex;
Why is thread local ugly?

You are confusing inconsistent state (as in your -O3 and -O0 example) with corrupt data. Mutex does not prevent the inconsistent state in your example, that's known. Mutex prevents corrupt data as show in the example below:
```
static std::string getTargetArchOption() {
  return (march != "") ? "--march=" + march : "";
}
```
With proper mutex, the above code will always return either `--march=something` or empty string. Without mutex, the code could return a half baked `--march=` string, which may cause other code to fail. Yes in this particular case the half baked string may not be harmful but that's not the point.