Split inferShapes and add verify to PRelu Op.
onnx/onnx-mlir pull request #1242
Opened 2022-03-15 15:22 UTC by redbopo

First pull request on onnx-mlir, mostly follow the code like Pow Op.
Maybe need to add some error test, but not quite sure.

2022-03-16 00:32 UTC, tungld reviewed
> Maybe need to add some error test, but not quite sure.

Yes, please add some lit tests for this.

2022-03-16 00:32 UTC, tungld commented on utils/gen_onnx_mlir.py
> +    'PRelu',
This should be added to `OpsWithVerifier` list instead of `OpsWithCanonicalizer` list.

2022-03-16 18:06 UTC, redbopo commented
Thanks @AlexandreEichenberger  and @tungld . 
I also notice the 
`func @test_pow_verifier_1()` in invalud.mlir with no expected-error,
And need another patch to fix it.

2022-03-22 00:58 UTC, tungld commented
@jenkins-droid test this please

2022-03-22 01:14 UTC, tungld commented
@redbopo could you resolve the conflict and fix the DCO issue? You can click on Details of DCO and follow the instruction.

> I also notice the func @test_pow_verifier_1() in invalud.mlir with no expected-error,

Thanks for finding this! It's ok to fix it here if you are interested.

2022-04-01 08:41 UTC, tungld commented
@redbopo any progress on this? thanks!

2022-04-07 15:15 UTC, redbopo commented
@tungld sorry for late reply. I will do a check soon.

2022-04-08 00:53 UTC, tungld commented
@jenkins-droid test this please

2022-04-13 13:59 UTC, redbopo commented
Hello @tungld , aggreed to CLA now, and merge the main branch.
Is that only first time to contribute  , 
will need this CLA and jenkins-droid cannot auto-run ?

2022-04-14 15:01 UTC, AlexandreEichenberger commented
I believe the first few times you need approval of folks with more privileges.

2022-08-22 02:22 UTC, tungld requested changes
I am sorry that I forgot to submit my review.

2022-08-22 02:23 UTC, tungld commented
@redbopo could you please resolve the conflicts and address the above comment? Thanks!

2022-08-31 14:45 UTC, redbopo commented on src/Dialect/ONNX/ONNXOps.cpp
> +  auto xShape = X().getType().cast<ShapedType>().getShape();
Fix now. @tungld

2022-09-01 05:33 UTC, tungld commented
@redbopo I saw clang-format failed with this info:
```diff
--- ./src/Dialect/ONNX/ONNXOps.cpp	(original)
+++ ./src/Dialect/ONNX/ONNXOps.cpp	(reformatted)
@@ -1133,7 +1133,8 @@
 
 LogicalResult ONNXPReluOp::verify() {
   ArrayRef<int64_t> xShape = X().getType().cast<ShapedType>().getShape();
-  ArrayRef<int64_t> slopeShape = slope().getType().cast<ShapedType>().getShape();
+  ArrayRef<int64_t> slopeShape =
+      slope().getType().cast<ShapedType>().getShape();
 
   // PRelu supports unidirectional broadcasting, that is slope should be
   // unidirectional broadcastable to input X.
```

Please update your code accordingly. Thanks!

2022-09-02 04:44 UTC, tungld commented
@redbopo you forgot signing DCO for some last commits, please sign and it's ready to merge. Thanks!

2022-09-02 11:32 UTC, redbopo commented
Sorry for that. DCO success now. @tungld

2022-09-02 11:39 UTC, tungld commented
@jenkins-droid test this please

2022-09-02 13:59 UTC, tungld approved these changes
LGTM. Thanks for your contribution!

2022-09-02 14:00 UTC, merged