Bug fixes for RunONNXModel.py
onnx/onnx-mlir pull request #1814
Opened 2022-10-28 22:45 UTC by Silvan-K

This PR addresses some minor bugs in RunONNXModel.py:

-  The option `--verify-all-ops` did not work in my use case because the intermediate tensors that were added to the models as outputs had no type associated to them which caused onnx-mlir to reject the model when trying to compile it
- The option `--load-so` did not work in combination with `--verify onnxruntime` did not work because the modified onnx model was not saved to the temporary directory

2022-10-31 00:40 UTC, tungld commented
@jenkins-droid test this please

2022-10-31 04:40 UTC, tungld requested changes
Thank you for the fixes! Please fix some typos and it's good to go.

2022-10-31 04:40 UTC, tungld commented on utils/RunONNXModel.py
> +    # Retrieven tensor value info for each intermediate output
typo: Retrieven => Retrieve

2022-10-31 04:40 UTC, tungld commented on utils/RunONNXModel.py
> +    # them will is an output of the model. If using onnxruntime for
`will is` -> `will be`

2022-10-31 19:10 UTC, silvan-lemurian commented on utils/RunONNXModel.py
> +    # them will is an output of the model. If using onnxruntime for
Thanks, fixed the typo

2022-10-31 19:10 UTC, silvan-lemurian commented on utils/RunONNXModel.py
> +    # Retrieven tensor value info for each intermediate output
Thanks, fixed the typo

2022-11-01 00:37 UTC, tungld commented
@jenkins-droid test this please

2022-11-01 00:37 UTC, tungld approved these changes
LGTM. Thanks!

2022-11-01 06:15 UTC, merged