Support Opset 20 for ReduceMin and ReduceMax
onnx/onnx-mlir pull request #2744
Opened 2024-03-07 22:59 UTC by hamptonm1

2024-03-14 17:30 UTC, hamptonm1 commented
@chentong319 @AlexandreEichenberger Let me know what you guys think and if I should make any further updates. Thanks!

2024-03-15 08:42 UTC, philass approved these changes
Other than that LGTM

It's a shame that a new op needs to be added for this, but I see how our current infrastructure makes that a necessity. This is beyond the scope of this PR, but we should rethink our versioning. In cases where the newer version is a super set of functionality with no breaking changes, we shouldn't have to add new ops.

2024-03-15 08:42 UTC, philass commented on src/Dialect/ONNX/ONNXOps/Math/Reduction.cpp
> +  return inferShapeForReductionOps_old<ONNXReduceMaxV18Op>(*this);
Shouldn't this be 
```
return inferShapeForReductionOps<ONNXReduceMaxV18Op>(*this);
```

2024-03-15 08:42 UTC, philass commented on src/Dialect/ONNX/ONNXOps/Math/Reduction.cpp
> +  return inferShapeForReductionOps_old<ONNXReduceMinV18Op>(*this);
Same here

2024-03-15 12:54 UTC, AlexandreEichenberger requested changes
Code seems fine but I would like to know why a new op is needed before we merge, as we should avoid new versions as much as possible

2024-03-15 20:50 UTC, AlexandreEichenberger approved these changes
LGTM after explanation, it makes sense.

2024-03-15 20:57 UTC, hamptonm1 commented
> LGTM after explanation, it makes sense.

@AlexandreEichenberger Thanks for the talk and I am glad everything makes sense now. Side point for reference if anyone wants to understand the reason why please view the description in this PR for clarity. Thanks!!

2024-03-15 21:06 UTC, hamptonm1 commented on src/Dialect/ONNX/ONNXOps/Math/Reduction.cpp
> +  return inferShapeForReductionOps_old<ONNXReduceMaxV18Op>(*this);
@philass Thanks for catching that!

2024-03-16 01:53 UTC, merged